### ISSUE TITLE
Optimize TOC height

### ISSUE THREAD

**Issue by kaushalmodi** [carsonip/hugo-theme-minos#3]
Hello,

Based on the below code:

```css
.article-toc {
  display: none;
  position: fixed;
  left: 50%;
  top: 110px;
  font-size: 0.9em;
  width: 260px;
  margin-left: 400px;
  padding-left: 20px;
  overflow-y: auto;
  line-height: 1.4em;
  max-height: 40.32em;
}
```

the TOC max height is limited to 40.32em.

Is it possible to make that dynamic.. based on the browser window height?

With the default, I see a lot of white space at the bottom and then a scrollbar for the TOC:

![image](https://cloud.githubusercontent.com/assets/3578197/23342875/19bfdc6c-fc30-11e6-8b6b-dcaa9e87aab2.png)
